// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvgIS24yoGpAGv6Ly89bKsxpIdTVTpKTw',
    appId: '1:807701533413:web:610fed8c48d3f2301c7a0c',
    messagingSenderId: '807701533413',
    projectId: 'mental-health-chat-8659e',
    authDomain: 'mental-health-chat-8659e.firebaseapp.com',
    storageBucket: 'mental-health-chat-8659e.firebasestorage.app',
    measurementId: 'G-R1SX8MK2GQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1aR18QaYiyF8Bu1yGM9wM_nDJ53L2XiA',
    appId: '1:807701533413:android:8de2dd01722baec11c7a0c',
    messagingSenderId: '807701533413',
    projectId: 'mental-health-chat-8659e',
    storageBucket: 'mental-health-chat-8659e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfe3tZwJyaWclqc2EzbBVxOFgI4BrPXAw',
    appId: '1:807701533413:ios:c51ac753aa4bcdda1c7a0c',
    messagingSenderId: '807701533413',
    projectId: 'mental-health-chat-8659e',
    storageBucket: 'mental-health-chat-8659e.firebasestorage.app',
    androidClientId: '807701533413-12tsc3t9mloqmg68h439hshg8sl5r06e.apps.googleusercontent.com',
    iosClientId: '807701533413-snmo0ehb1lqrt8i4t8kegdcf26slnjr5.apps.googleusercontent.com',
    iosBundleId: 'com.mindmate.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfe3tZwJyaWclqc2EzbBVxOFgI4BrPXAw',
    appId: '1:807701533413:ios:1c7535389531f5d51c7a0c',
    messagingSenderId: '807701533413',
    projectId: 'mental-health-chat-8659e',
    storageBucket: 'mental-health-chat-8659e.firebasestorage.app',
    androidClientId: '807701533413-12tsc3t9mloqmg68h439hshg8sl5r06e.apps.googleusercontent.com',
    iosClientId: '807701533413-nlhj1uj0k54fi3g0n8i1bme60dag5df2.apps.googleusercontent.com',
    iosBundleId: 'com.kohang.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvgIS24yoGpAGv6Ly89bKsxpIdTVTpKTw',
    appId: '1:807701533413:web:4582b11a1504adb71c7a0c',
    messagingSenderId: '807701533413',
    projectId: 'mental-health-chat-8659e',
    authDomain: 'mental-health-chat-8659e.firebaseapp.com',
    storageBucket: 'mental-health-chat-8659e.firebasestorage.app',
    measurementId: 'G-XP3KVWTT0S',
  );

}
